version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13.10-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: danil68/foodgram_backend
    env_file: .env
    volumes:
    - static:/backend_static
    - media:/app/media
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    image: danil68/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - backend

  nginx:
    image: danil68/foodgram_gateway
    ports:
      - "8000:80"
    volumes:
      - static:/static
      - media:/media:ro
    depends_on:
      - backend
