# Generated by Django 3.2.3 on 2024-08-17 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20240817_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='short_link',
            new_name='short_code',
        ),
    ]
